<template>
    <!-- We can use evetn modifiers as "self" to specify that this will only occur, when it is clicked, and not its child elements -->
    <div class="backdrop" @click.self="closeModal">
        <!-- Dynamic class: we add the class "theme_sale" if the condition "theme === 'sale'" is true -->
        <div class="modal" :class="{ default_theme: cleanModal, slide_in_bottom: !CloseAnimation, slide_out_bottom_out: CloseAnimation }">
            <!-- The text inside the slot is the default, if no other is given -->
            <div class="modal_content">
                <slot></slot>
            </div>
        </div>
    </div>
</template>

<script>
export default {
    props: [ 'cleanModal' ],

    data() {
        return{
            CloseAnimation: false
        }
    },

    methods: {
        // This is a custom event and can be used to fire funtions from the child component in the parent component.
        // The name of the event emitted, in this case "close", can be whatever we want it to be named
        closeModal() {
            this.CloseAnimation = true

            setTimeout(()=>{
                this.Close()
            },350);
            
            $('.backdrop').animate({
                opacity: 0
            }, 300)
        },

        Close() {
            this.$emit('close')
        }
    },

    mounted() {
        
    }
}
</script>


<style>
    .modal {
        width: 85%;
        padding: 4px;
        margin: 100px auto;
        background: rgb(254,0,1);
        background: -moz-linear-gradient(120deg, rgba(254,0,1,1) 0%, rgba(90,111,253,1) 100%);
        background: -webkit-linear-gradient(120deg, rgba(254,0,1,1) 0%, rgba(90,111,253,1) 100%);
        background: linear-gradient(120deg, rgba(254,0,1,1) 0%, rgba(90,111,253,1) 100%);
        filter: progid:DXImageTransform.Microsoft.gradient(startColorstr="#fe0001",endColorstr="#5a6ffd",GradientType=1);
        -webkit-box-shadow: 0px 3px 25px -4px rgba(0,0,0,0.4);
        -moz-box-shadow: 0px 3px 25px -4px rgba(0,0,0,0.4);
        box-shadow: 0px 3px 25px -4px rgba(0,0,0,0.4);
    }

    .default_theme {
        width: 85%;
        padding: 9px;
        margin: 100px auto;
        background: white;
        -webkit-box-shadow: 0px 3px 25px -4px rgba(0,0,0,0.4);
        -moz-box-shadow: 0px 3px 25px -4px rgba(0,0,0,0.4);
        box-shadow: 0px 3px 25px -4px rgba(0,0,0,0.4);
    }

    .backdrop {
        top: 0;
        position: fixed;
        background: rgba(0,0,0,0.5);
        width: 100%;
        height: 100%;
        z-index: 2001;
    }

    .modal_content {
        background-color: white;
        height: 100%;
        width: 100%;
    }

    .slide_out_bottom_out {
	-webkit-animation: slide_out_bottom_out 0.3s cubic-bezier(0.550, 0.085, 0.680, 0.530) both;
	        animation: slide_out_bottom_out 0.3s cubic-bezier(0.550, 0.085, 0.680, 0.530) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2022-5-30 12:31:42
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-out-bottom
 * ----------------------------------------
 */
@-webkit-keyframes slide_out_bottom_out {
  0% {
    -webkit-transform: translateY(0);
            transform: translateY(0);
    opacity: 1;
  }
  100% {
    -webkit-transform: translateY(1000px);
            transform: translateY(1000px);
    opacity: 0;
  }
}
@keyframes slide_out_bottom_out {
  0% {
    -webkit-transform: translateY(0);
            transform: translateY(0);
    opacity: 1;
  }
  100% {
    -webkit-transform: translateY(1000px);
            transform: translateY(1000px);
    opacity: 0;
  }
}


    .slide_in_bottom {
        -webkit-animation: slide_in_bottom 0.3s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
                animation: slide_in_bottom 0.3s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
    }

        /* ----------------------------------------------
    * Generated by Animista on 2022-5-30 11:32:52
    * Licensed under FreeBSD License.
    * See http://animista.net/license for more info. 
    * w: http://animista.net, t: @cssanimista
    * ---------------------------------------------- */

    /**
    * ----------------------------------------
    * animation slide-in-bottom
    * ----------------------------------------
    */
    @-webkit-keyframes slide_in_bottom {
    0% {
        -webkit-transform: translateY(1000px);
                transform: translateY(1000px);
        opacity: 0;
    }
    100% {
        -webkit-transform: translateY(0);
                transform: translateY(0);
        opacity: 1;
    }
    }
    @keyframes slide_in_bottom {
    0% {
        -webkit-transform: translateY(1000px);
                transform: translateY(1000px);
        opacity: 0;
    }
    100% {
        -webkit-transform: translateY(0);
                transform: translateY(0);
        opacity: 1;
    }
    }


</style>